---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: quotes
- name: version

outputs:
- name: build

params:
  TERM: dumb

run:
  path: quotes/ci/build.sh
